// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicShop.Models;

#nullable disable

namespace MusicShop.Migrations
{
    [DbContext(typeof(MusicShopDbContext))]
    partial class MusicShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("MusicShop.Models.Disk", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Artwork")
                        .HasColumnType("BLOB")
                        .HasColumnName("artwork");

                    b.Property<long?>("CurrentYearSells")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_year_sells")
                        .HasDefaultValueSql("0");

                    b.Property<string>("DateRelease")
                        .HasColumnType("TEXT(10, 10)")
                        .HasColumnName("date_release");

                    b.Property<long?>("LastYearSells")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_year_sells")
                        .HasDefaultValueSql("0");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT(50)")
                        .HasDefaultValue("0")
                        .HasColumnName("name");

                    b.Property<double>("RetailPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("retail_price");

                    b.Property<int>("SellerCompanyId")
                        .HasColumnType("seller_company_id");

                    b.Property<double>("WholesalePrice")
                        .HasColumnType("REAL")
                        .HasColumnName("wholesales_price");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("disk", (string)null);
                });

            modelBuilder.Entity("MusicShop.Models.DiskRecords", b =>
                {
                    b.Property<int>("DiskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusicVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiskId", "MusicVersionId");

                    b.HasIndex("MusicVersionId");

                    b.ToTable("DiskRecords");
                });

            modelBuilder.Entity("MusicShop.Models.Ensemble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT(50)");

                    b.HasKey("Id");

                    b.ToTable("Ensemble", (string)null);
                });

            modelBuilder.Entity("MusicShop.Models.EnsembleMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnsembleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusicianId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnsembleId");

                    b.HasIndex("MusicianId");

                    b.ToTable("EnsembleMembership");
                });

            modelBuilder.Entity("MusicShop.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "manufacturer_name_unique")
                        .IsUnique();

                    b.ToTable("Manufacturer", (string)null);
                });

            modelBuilder.Entity("MusicShop.Models.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Artwork")
                        .HasColumnType("blob");

                    b.Property<string>("MusicDuration")
                        .HasColumnType("TEXT(5, 5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT(50)");

                    b.HasKey("Id");

                    b.ToTable("Music", (string)null);
                });

            modelBuilder.Entity("MusicShop.Models.MusicAuthors", b =>
                {
                    b.Property<int>("EnsembleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnsembleId", "MusicId");

                    b.HasIndex("MusicId");

                    b.ToTable("MusicAuthors");
                });

            modelBuilder.Entity("MusicShop.Models.MusicVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("MusicId");

                    b.HasIndex("PerformerId");

                    b.ToTable("MusicVersions", (string)null);
                });

            modelBuilder.Entity("MusicShop.Models.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("BLOB");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT(50)");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT(50)");

                    b.HasKey("Id");

                    b.ToTable("Musician", (string)null);
                });

            modelBuilder.Entity("MusicShop.Models.SellerCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "seller_company_name_unique")
                        .IsUnique();

                    b.ToTable("SellerCompany", (string)null);
                });

            modelBuilder.Entity("MusicShop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text(5, 50)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .HasColumnType("text(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Login" }, "user_login_unique")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MusicShop.Models.Disk", b =>
                {
                    b.HasOne("MusicShop.Models.Manufacturer", "Manufacturer")
                        .WithMany("Disks")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicShop.Models.SellerCompany", "SellerCompany")
                        .WithMany("Disks")
                        .HasForeignKey("SellerCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("MusicShop.Models.DiskRecords", b =>
                {
                    b.HasOne("MusicShop.Models.Disk", "Disk")
                        .WithMany()
                        .HasForeignKey("DiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicShop.Models.MusicVersion", "MusicVersion")
                        .WithMany()
                        .HasForeignKey("MusicVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disk");

                    b.Navigation("MusicVersion");
                });

            modelBuilder.Entity("MusicShop.Models.EnsembleMembership", b =>
                {
                    b.HasOne("MusicShop.Models.Ensemble", "Ensemble")
                        .WithMany("Memberships")
                        .HasForeignKey("EnsembleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicShop.Models.Musician", "Musician")
                        .WithMany("Memberships")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ensemble");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("MusicShop.Models.MusicAuthors", b =>
                {
                    b.HasOne("MusicShop.Models.Ensemble", "Ensemble")
                        .WithMany()
                        .HasForeignKey("EnsembleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicShop.Models.Music", "Music")
                        .WithMany()
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ensemble");

                    b.Navigation("Music");
                });

            modelBuilder.Entity("MusicShop.Models.MusicVersion", b =>
                {
                    b.HasOne("MusicShop.Models.Music", "Music")
                        .WithMany("MusicVersions")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicShop.Models.Ensemble", "Performer")
                        .WithMany("MusicVersions")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Music");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("MusicShop.Models.Ensemble", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("MusicVersions");
                });

            modelBuilder.Entity("MusicShop.Models.Manufacturer", b =>
                {
                    b.Navigation("Disks");
                });

            modelBuilder.Entity("MusicShop.Models.Music", b =>
                {
                    b.Navigation("MusicVersions");
                });

            modelBuilder.Entity("MusicShop.Models.Musician", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("MusicShop.Models.SellerCompany", b =>
                {
                    b.Navigation("Disks");
                });
#pragma warning restore 612, 618
        }
    }
}
